// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpLyJEfCDelS4FBaR9TVIl51x2263K_8M',
    appId: '1:175673775936:web:8e02b631a6414089938ca5',
    messagingSenderId: '175673775936',
    projectId: 'nawadurgafruits',
    authDomain: 'nawadurgafruits.firebaseapp.com',
    storageBucket: 'nawadurgafruits.appspot.com',
    measurementId: 'G-NC6W3SFVH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnBjadYzDqHz0s_xZevAOxM04JJOv3y9A',
    appId: '1:175673775936:android:da87f21ac5ba7af3938ca5',
    messagingSenderId: '175673775936',
    projectId: 'nawadurgafruits',
    storageBucket: 'nawadurgafruits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAgvhz-BGHqJU1SclRdH23vZuqtFuHvkI',
    appId: '1:175673775936:ios:182d968b2d4fa0cc938ca5',
    messagingSenderId: '175673775936',
    projectId: 'nawadurgafruits',
    storageBucket: 'nawadurgafruits.appspot.com',
    iosBundleId: 'com.example.navadurgaFruits',
  );
}
